# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: deepseek config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
{
  "models": [
    {
      "title": "DeepSeek",
      "provider": "openai",
      "model": "deepseek-chat",
      "apiKey": "sk-ba09379b1ed8436691ccfc8536248b8c",
      "apiBase": "https://api.deepseek.com/v1"
    }
  ]
}
# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
